FROM golang:1.24-alpine

WORKDIR /app

# Install dependencies
RUN apk add --no-cache git gcc musl-dev

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build worker binary
RUN go build -o /usr/local/bin/worker ./cmd/worker

# Command to run worker
CMD ["worker"]