// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/evrintobing17/expense-management-backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

// ProcessPayment provides a mock function with given fields: ctx, amount, externalID
func (_m *PaymentService) ProcessPayment(ctx context.Context, amount int, externalID string) (*domain.PaymentResponse, error) {
	ret := _m.Called(ctx, amount, externalID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPayment")
	}

	var r0 *domain.PaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (*domain.PaymentResponse, error)); ok {
		return rf(ctx, amount, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) *domain.PaymentResponse); ok {
		r0 = rf(ctx, amount, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, amount, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentService creates a new instance of PaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentService {
	mock := &PaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
